version: '3.9'

services:
  database:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: taikhau
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nhom1-database
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
    container_name: backend-container
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/nhom1-database
      SPRING_DATASOURCE_USERNAME: taikhau
      SPRING_DATASOURCE_PASSWORD: 123
    depends_on:
      - database
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./frontend
    container_name: frontend-container
    depends_on:
      - backend
    ports:
      - "9090:9090"

volumes:
  postgres-data:
